sudo: false
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "nightly"

matrix:
    fast_finish: true
    include:
        - env: TOXENV=qa
          python: 3.7
        - env: TOXENV=py37-openpyxl24
          python: 3.7

    allow_failures:
          python: "3.7"
        - env: TOXENV=qa
        - python: "3.9-dev"
        - python: "nightly"

install: pip install tox-travis python-coveralls codecov
script: tox

after_success:
  - codecov -e TOXENV
